name: Build All Branches

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Zulu JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make gradlew Executable
        run: chmod +x ./gradlew

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.OPENLINK_BOT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          branches=("1.16.5" "master" "1.19.2" "1.20.1" "1.20.4" "1.21" "1.21.4" "1.21.5")
          
          for ((i=0; i<${#branches[@]}; i++)); do
            git checkout ${branches[i]} || git checkout -b ${branches[i]}
            ./gradlew build
          done

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ github.ref_name }}
          path: |
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar
            quilt/build/libs/*.jar
